### ISSUE TITLE
Segmentation violation after connecting via zeroconf in v0.1 when connecting from Spotify desktop

### ISSUE THREAD

**Issue by l3d00m** [devgianlu/go-librespot#130]
With the newest version, I get this error immediately after trying to connect via zeroconf. This happens every time I try to connect from my Spotify Linux Desktop client, it works from my android spotify app tho.

```
INFO[0000] running go-librespot v0.1.0
INFO[0000] zeroconf server listening on port 42651
INFO[0009] authenticated AP as USERNAME
INFO[0009] authenticated Login5 as USERNAME
INFO[0009] accepted zeroconf user USERNAME from thomas-manjaro
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x14 pc=0x4c2484]

goroutine 76 [running]:
github.com/devgianlu/go-librespot/spclient.NewContextResolver(0x13ed6e0, 0x1282bc0)
	/src/spclient/context_resolver.go:55 +0x244
github.com/devgianlu/go-librespot/tracks.NewTrackListFromContext(0x13ed6e0, 0x1282bc0)
	/src/tracks/tracks.go:29 +0x38
main.(*AppPlayer).handlePlayerCommand(0x11b21e0, {0x39ee6d8b, {0x10b6ed0, 0x28}, {{0x129bdf0, 0x8}, {0x0, 0x0}, {0x11c0f50, 0x4e, ...}, ...}})
	/src/cmd/daemon/player.go:154 +0xe20
main.(*AppPlayer).handleDealerRequest(0x11b21e0, {0x1098c00, {0x10b60c0, 0x24}, {0x39ee6d8b, {0x10b6ed0, 0x28}, {{0x129bdf0, 0x8}, {0x0, ...}, ...}}})
	/src/cmd/daemon/player.go:347 +0xe4
main.(*AppPlayer).Run(0x11b21e0, 0x1412fc0)
	/src/cmd/daemon/player.go:570 +0x470
created by main.(*App).withAppPlayer.func3 in goroutine 1
	/src/cmd/daemon/main.go:343 +0x4cc
```

Happening also with the default config (i.e. none)

**Comment by devgianlu** [comment]
Thank you for reporting! Shoul be fixed.
